_BASE_: "../base/faster_rcnn_R_50_FPN.yaml"
AL:
  DATASET:
    IMAGE_BUDGET: 1200
  OBJECT_FUSION:
    BUDGET_ETA: 0.4
    INITIAL_RATIO: 0.90
    LAST_RATIO: 0.40
    REMOVE_DUPLICATES_TH: 0.25
  TRAINING:
    EPOCHS_PER_ROUND_INITIAL: 20
    EPOCHS_PER_ROUND_LAST: 10
    ROUNDS: 10
MODEL:
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 6
TEST: 
  DETECTIONS_PER_IMAGE: 100