_BASE_: "../base/faster_rcnn_R_50_FPN.yaml"
AL:
  DATASET:
    IMAGE_BUDGET: 240
  OBJECT_FUSION:
    BUDGET_ETA: 0.4
    INITIAL_RATIO: 0.90
    LAST_RATIO: 0.75
    REMOVE_DUPLICATES_TH: 0.25
  TRAINING:
    EPOCHS_PER_ROUND_INITIAL: 200
    EPOCHS_PER_ROUND_LAST: 120
    ROUNDS: 4
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 5
    SCORE_THRESH_TEST: 0.5
    NMS_THRESH_TEST: 0.5
SOLVER:
  IMS_PER_BATCH: 6
TEST: 
  DETECTIONS_PER_IMAGE: 100
