_BASE_: "../faster_rcnn_R_50_FPN.yaml"
AL:
  OBJECT_SCORING: perturbation
  OBJECT_FUSION:
    DECAY: geometry
    LAST_RATIO: 0.50
  PERTURBATION:
    VERSION: 4
    ALPHAS: [0.04, 0.08]
    BETAS: [0.04, 0.08]